tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "remotemobprogramming/brew"
brew "awscli"
brew "adr-tools"
brew "coreutils"
# didn't work: brew "gcc" # for pyenv, for chalice, CC=/opt/homebrew/bin/gcc-12 pyenv install 3.9.16
brew "diff-pdf"
brew "graphviz"
brew "jq"
# didn't work: brew "pyenv"
brew "python@3.9" # /opt/homebrew/bin/python3.9
brew "remotemobprogramming/brew/mob"
brew "thefuck"
brew "tree"
brew "watch"
cask "docker"
cask "google-chrome"
cask "kdiff3"
cask "keepassxc"
cask "slack"
cask "spotify"
cask "zoom"
brew "rbenv"
brew "ruby-build"
brew "openresty/brew/openresty"
brew "lua51"
brew "luarocks"
brew "node@14"

